"""Arrange the results website around solution, code-backed method and follow-up."""
import re

METHOD=r'''<h2>Methodology</h2><p class="sectionIntro">Every stage below identifies what the provider supplied, what EcoOrbit executes, and which output the judges can reproduce. The gas analysis uses physics and quality rules; machine learning provides supplementary site context.</p>
<div class="grid3"><div class="card"><div class="label">Hyperspectral example 1</div><h3>EMIT methane pixels</h3><p>Three real observations: Jeddah and two Seropédica dates. NASA retrieves methane enhancement from spectral absorption; EcoOrbit analyzes the delivered enhancement, geometry, wind and selected plume mass.</p></div><div class="card"><div class="label">Hyperspectral example 2</div><h3>Tanager site classification</h3><p>Real surface-reflectance spectra from 48 US sites. Spectral bins and indices feed a supervised industrial-versus-school screen and a separate material-cluster visualization.</p></div><div class="card"><div class="label">Multispectral example</div><h3>Sentinel-2 + Landsat</h3><p>Sentinel-2 red, near-infrared and shortwave-infrared bands measure vegetation and built-surface change. Landsat surface-temperature bands show site-versus-surrounding heat.</p></div></div>
<div class="card wide" style="margin-top:18px"><h3>Preprocessing: provider products versus EcoOrbit code</h3><div class="tableWrap"><table><thead><tr><th>Stage</th><th>Implemented behavior</th><th>Evidence / code</th></tr></thead><tbody>
<tr><td>1 · Acquire and register</td><td>Retain NASA plume TIFF/GeoJSON, source-scene IDs and real ERA5 responses. Download Tanager imagery by scene ID; geocode training sites from EPA and OSM records.</td><td><code>data/real_emit/</code><br><code>src/multisite_download.py</code><br><code>data/training_sites.csv</code></td></tr>
<tr><td>2 · Calibration and atmospheric correction</td><td>NASA provides gas enhancement retrievals; Tanager L2A provides surface reflectance; Sentinel-2 L2A and Landsat C2 L2 are provider-processed inputs. EcoOrbit does not independently perform radiance calibration or atmospheric retrieval. Landsat digital temperature values are scaled to physical temperature.</td><td><code>src/train_classifier.py</code><br><code>src/site_heat.py</code><br><code>src/site_land.py</code></td></tr>
<tr><td>3 · Geometry and quality</td><td>Use supplied georeferencing. Map site coordinates into the source image projection; sample/reproject local windows. Reject clouds, cirrus and no-data. Calculate actual WGS84 cell areas for plume mass.</td><td><code>src/train_classifier.py</code><br><code>src/emit_pixels.py</code><br><code>src/emit_cases.py</code></td></tr>
<tr><td>4 · Hyperspectral binning</td><td>Tanager: 11 × 11 neighborhoods; ≥50 valid pixels and a valid centre. Average bands into 30 nm bins, omit strong water-absorption intervals, then take the spatial median. Calculate NDVI, NDBI and MNDWI.</td><td><code>src/train_classifier.py: site_features</code><br><code>results/real/classifier/site_spectral_features.csv</code></td></tr>
<tr><td>5 · Gas pixel preparation</td><td>Jeddah: ENH/SENS, sensitivity range 0.5–2, nearby background subtraction and ≥2× uncertainty screen. Brazil: vetted plume enhancement values and polygon; no invented companion correction or uncertainty. Compare 500/1000/1500 ppm·m thresholds.</td><td><code>src/emit_pixels.py</code><br><code>src/emit_cases.py</code><br><code>analysis_mask.tif</code></td></tr>
<tr><td>6 · Multispectral preparation</td><td>Sentinel-2: B04/B08/B11 on a 20 m grid with SCL classes 4/5/7; median NDVI/NDBI within 180 m and a 500–1000 m reference ring. Landsat: QA mask, scale/offset and Celsius conversion; 180 m site and 600–1200 m ring.</td><td><code>src/site_land.py</code><br><code>src/site_heat.py</code><br><code>results/real/land/</code></td></tr>
</tbody></table></div></div>
<div class="grid" style="margin-top:18px"><div class="card"><div class="label">Analysis · implemented</div><h3>From pixels to methane evidence</h3><p>Intersect the NASA plume boundary with quality-selected pixels. Convert enhancement to column mass using the ideal gas law and each pixel's area; sum to integrated excess methane. Combine real overpass wind with mass and a whole-complex span to calculate diagnostic flux scenarios.</p><p><code>Q = 3600 × wind × integrated mass / span</code></p><p>Selected mass is a snapshot quantity. A diagnostic flux becomes a defensible source rate only after source geometry, appropriate wind and uncertainty checks. No annual landfill inventory is inferred.</p><p class="tiny">Reproduce: <code>python -m src.emit_cases</code></p></div><div class="card"><div class="label">Machine learning · supplementary</div><h3>Site classification, evaluated honestly</h3><p>Median imputation → standardization → PCA → balanced logistic regression. The fixed test contains 12 sites across all three cities; 36 sites train the model. Three-fold training-only validation selects among 4/8/12 PCA components.</p><p><strong>11/12 correct · accuracy 91.7% · AUC 0.944</strong></p><p>Labels are industrial registry sites versus school controls. This is a small contextual screen, not a validated landfill classifier or an ML methane-emission estimator. Green patches test vegetation context without entering the supervised test.</p><p class="tiny"><code>src/evaluate_sites.py</code> · <code>python -m src.evaluate_sites</code></p></div></div>
<div class="card wide" style="margin-top:18px"><h3>Reproducible outputs and judge walkthrough</h3><p><strong>Solution:</strong> select a real plume event, inspect its pixels and wind, compare threshold-dependent mass and diagnostic flux, then inspect the separate published CO₂ reference.</p><p><strong>Additional features:</strong> inspect the US site map, hyperspectral classification, Sentinel-2 changes, Landsat heat and relevant NO₂/SO₂ observations. These are separate US examples; they are not automatically matched to the landfill events.</p><p><code>python -m src.emit_cases</code> → <code>python -m src.evaluate_sites</code> → <code>python -m src.build_website</code></p><p>Notebooks: <code>02_main_analysis.ipynb</code> and <code>04_emit_pixel_analysis.ipynb</code>. Bundled real outputs and small source crops support offline reproduction; full raw imagery has separate download commands.</p></div>'''

def reframe(content):
 sections={name:body for name,body in re.findall(r'<section id="([^"]+)" class="section(?: active)?">(.*?)</section>',content,re.S)}
 overview=sections['overview']
 overview=overview.replace('What the evidence shows','Methane and carbon intelligence')
 overview=overview.replace('A screening system that combines site spectra, land-surface and atmosphere products. Every view retains its spatial scale and missing-data status.','Inspect real methane plumes and carbon evidence, retain acquisition and wind context, and produce traceable investigation outputs. Additional site analysis supports follow-up rather than replacing direct gas evidence.')
 # Retain the site map IDs for existing rendering; move this context to additional page.
 m=re.search(r'<div class="grid"><div class="card"><h3>Where the US pilot sits</h3>.*?</div></div></section>',content,re.S)
 mapcard='<div class="card"><h3>US supplemental site locations</h3><div id="map-overview"></div><div id="map-details" class="tiny muted">Select a site marker.</div></div>'
 # Replace overview cards with the concise solution narrative, no duplicate map IDs.
 overview=re.split(r'<div class="grid3">',overview)[0]+'''<div class="grid3"><div class="card"><div class="label">Detect</div><h3>Real hyperspectral methane</h3><p>NASA EMIT plume pixels for one Jeddah and two Seropédica observations, with enhancement maps and threshold controls.</p></div><div class="card"><div class="label">Investigate</div><h3>Wind, mass and source checks</h3><p>Review selected excess methane and diagnostic flux alongside real ERA5 wind. Source attribution and flux validity remain separate decisions.</p></div><div class="card"><div class="label">Report</div><h3>Traceable carbon evidence</h3><p>Separate EcoOrbit's methane calculations from source-reported CO₂ examples and GRI/GHG Protocol inventory requirements.</p></div></div>'''
 plume=sections['plumes'].replace('Plumes & methane','Published CH₄ and CO₂ reference evidence').replace('Real published plume examples show what source-resolved detection can look like. The Landfill methane tab provides EcoOrbit\'s direct analysis of uploaded NASA observations.','These provider-reported observations demonstrate gas-resolved methane and carbon dioxide measurements at other sites. EcoOrbit does not claim to have retrieved these CO₂ pixels or measured CO₂ at the two landfill sites.')
 air=sections['air'].replace('Air & wind','Relevant NO₂/SO₂ and wind').replace('Choose a city and atmospheric product. Sentinel-5P NO₂/SO₂ columns and Sentinel-2 aerosol optical thickness are observations; CAMS concentrations are modeled regional context.','QA-screened Sentinel-5P columns near US industrial coordinates provide supporting gas context. These observations are not coincident measurements of the landfill plumes.')
 air=re.sub(r'<select id="airgas">.*?</select>','<select id="airgas"><option>NO2</option><option>SO2</option></select>',air,flags=re.S)
 air=air.replace('AOT represents optical aerosol load without identifying a chemical species. ','')
 land=sections['land'].replace('Land & heat','Multispectral follow-up and hyperspectral site context')
 esg=sections['esg'].replace('ESG evidence & methods','Reporting and interpretation')
 solution=overview+'<!--PIXEL_PANEL-->'+plume+'<div class="note">CO₂ is represented by source-reported reference evidence, not a new landfill CO₂ retrieval. No annual CO₂e inventory is calculated from these snapshots.</div>'
 method=METHOD+esg
 additional='<h2>Additional features</h2><p class="sectionIntro">Use these completed US pilot analyses to investigate site context: hyperspectral land materials, multispectral vegetation/built surfaces, surface heat, and relevant NO₂/SO₂ columns. They are supplementary examples with their own locations and dates.</p>'+mapcard+land+air
 combined='<section id="solution" class="section active">'+solution+'</section><section id="methodology" class="section">'+method+'</section><section id="additional" class="section">'+additional+'</section>'
 content=re.sub(r'<section id="overview" class="section active">.*?</section></main>',lambda _:combined+'</main>',content,flags=re.S)
 content=re.sub(r'<nav class="nav".*?</nav>','<nav class="nav" aria-label="Main navigation"><button class="active" data-tab="solution">Solution</button><button data-tab="methodology">Methodology</button><button data-tab="additional">Additional features</button></nav>',content,flags=re.S)
 content=content.replace('Environmental intelligence from orbit.','Methane and carbon intelligence.').replace('Explore real hyperspectral land observations, published methane and carbon dioxide plumes, regional atmospheric context, heat, wind, and evidence gaps across an industrial pilot.','Real hyperspectral methane observations, traceable carbon evidence, and multispectral site context in a reproducible proof of concept.')
 content=content.replace('function go(id){','function go(id){id=({overview:"solution",plumes:"solution",landfills:"solution",esg:"methodology",air:"additional",land:"additional"})[id]||id;').replace("if(id==='land')renderLand()","if(id==='additional')renderLand()")
 return content
