"""Offline interactive views of three real landfill plume observations."""
import json,base64,csv

def fragment(root):
 path=root/'results/real/emit_pixels/case_summaries.json'
 if not path.exists():return '', ''
 cases=[]
 for s in json.loads(path.read_text()):
  out=root/'results/real/emit_pixels'/s['case_id'];rows=list(csv.DictReader((out/'selected_pixels.csv').open()))
  pixels=[]
  for r in rows:
   pixels.append({'latitude':round(float(r['latitude']),6),'longitude':round(float(r['longitude']),6),'enhancement':round(float(r.get('analysis_enhancement_ppmm',r.get('corrected_minus_background_ppmm'))),3),'sigma':round(float(r['sensor_uncertainty_ppmm']),3) if r['sensor_uncertainty_ppmm'] else None,'mass':round(float(r['excess_ch4_kg']),5)})
  cases.append({'summary':s,'pixels':pixels,'image':'data:image/png;base64,'+base64.b64encode((out/'pixel_analysis.png').read_bytes()).decode()})
 card='''<div class="card wide" style="margin:20px 0"><div class="label">Real NASA EMIT pixel measurements</div><h3>Landfill methane observations</h3><p>Three processed satellite observations with pixel enhancement, integrated excess methane, overpass wind and threshold sensitivity. Select an event to inspect its measured pixels.</p><div class="controls"><label for="pxcase">Observation</label><select id="pxcase"><option value="0">Jeddah · 9 June 2024</option><option value="1">Seropédica · 5 March 2024</option><option value="2">Seropédica · 24 September 2024</option></select><label for="pxthreshold">Threshold ppm·m</label><select id="pxthreshold"><option>500</option><option>1000</option><option>1500</option></select></div><div id="pxmethod"></div><img id="pximage" class="img" alt="Observed methane pixels and analysis mask"><div id="pxmap"></div><p class="tiny">Hover over a square to inspect a real selected pixel. This coordinate map is offline; red cross marks the approximate landfill coordinate.</p><div id="pxnumbers"></div><div class="note">Integrated excess mass describes methane present in selected pixels. The flux calculations below are diagnostic whole-complex scenarios, not validated facility emissions. They are excluded from annual inventories.</div><div id="pxscenario"></div><details><summary>Method, sources and interpretation</summary><div id="pxdetails"></div></details></div>'''
 script='<script>const PXC='+json.dumps(cases,ensure_ascii=False).replace('</','<\\/')+r''';function renderPixels(){const c=PXC[Number($('pxcase').value)],s=c.summary,q=Number($('pxthreshold').value),a=c.pixels.filter(p=>p.enhancement>=q),site=s.site_id==='jeddah_landfill'?[39.390260,21.644194]:[-43.760558,-22.795703],xs=c.pixels.map(p=>p.longitude).concat([site[0]]),ys=c.pixels.map(p=>p.latitude).concat([site[1]]),lo=Math.min(...xs),hi=Math.max(...xs),bot=Math.min(...ys),top=Math.max(...ys),X=x=>35+(x-lo)/(hi-lo)*620,Y=y=>320-(y-bot)/(top-bot)*280;$('pximage').src=c.image;$('pxmethod').innerHTML='<p><strong>'+esc(s.observed_utc)+'</strong> · '+esc(s.processing_mode)+'</p>';$('pxmap').innerHTML='<svg class="viz" viewBox="0 0 700 360" role="img" aria-label="Selected real methane pixels">'+a.map(p=>'<rect x="'+X(p.longitude)+'" y="'+Y(p.latitude)+'" width="3" height="3" fill="hsl('+(55-55*Math.min(p.enhancement/Math.max(...c.pixels.map(x=>x.enhancement)),1))+',95%,60%)"><title>Latitude '+p.latitude+'; longitude '+p.longitude+'; enhancement '+p.enhancement+' ppm m; '+(p.sigma!=null?'sensor sigma '+p.sigma+' ppm m; ':'')+'excess mass '+p.mass+' kg</title></rect>').join('')+'<path d="M'+(X(site[0])-6)+' '+Y(site[1])+'h12 M'+X(site[0])+' '+(Y(site[1])-6)+'v12" stroke="#ff6b70" stroke-width="2"/><text x="20" y="348">Longitude '+lo.toFixed(3)+' to '+hi.toFixed(3)+' · Latitude '+bot.toFixed(3)+' to '+top.toFixed(3)+'</text></svg>';const r=s.scenarios.find(x=>x.threshold_ppmm===q);$('pxnumbers').innerHTML='<p><strong>'+r.selected_pixels+' selected pixels · '+r.integrated_excess_ch4_kg.toFixed(0)+' kg integrated excess methane</strong><br>ERA5 wind '+s.wind_m_s.toFixed(2)+' m/s, from '+s.wind_from_deg.toFixed(0)+'° · Peak raw enhancement '+s.max_raw_enhancement_ppmm.toFixed(0)+' ppm·m</p>';let columns=[['threshold_ppmm','Threshold ppm·m'],['fetch_m','Whole-complex span m'],['hypothetical_simple_ime_kg_h','Diagnostic flux kg/h']];if(r.partial_sigma_kg_h!=null)columns.push(['partial_sigma_kg_h','Partial assumed 1σ kg/h']);$('pxscenario').innerHTML=table(s.scenarios,columns);$('pxdetails').innerHTML='<p>NASA source scene: <code>'+esc(s.source_scene)+'</code>. Pixel areas use WGS84 geodesy; methane mass uses the ideal gas law with recorded ERA5 pressure and temperature. Diagnostic Q = 3600 × wind × integrated mass / maximum selected-pixel separation.</p><p>Wind: '+esc(s.wind_source)+'; grid '+s.wind_grid_lat+', '+s.wind_grid_lon+'; valid time '+esc(s.wind_time_utc)+'.</p><ul>'+s.limitations.map(x=>'<li>'+esc(x).replaceAll('pending','unverified')+'</li>').join('')+'</ul>';} $('pxcase').onchange=renderPixels;$('pxthreshold').onchange=renderPixels;renderPixels();</script>'''
 return card,script
